Server client connection
fi-ya/http-server pull request #1
Opened 2022-05-26 16:55 UTC by fi-ya

This pull request refers to this [trello](https://trello.com/b/g7UHpv0V/apprenticeship) and includes the following:
- server socket created successfully
- client socket connection successfully
- client socket input/output streams handled using BufferedReader/PrintWriter
- used netcat to get client request
- client response sent successfully

To run [acceptance test](https://github.com/8thlight/http_server_spec/tree/master/features/01_getting_started), run program `./gradlew run`, cd into http_server_spec and run `rake test:f1 # Run all of the tests in 01_getting_started` 
**Acceptance test :** 
- [x] pass for Simple GET & Simple HEAD 
(21) Successful, (0) Pending, (0) Undefined, (4) Failed, (2) Error

- [x] circleci build & test passing 

Thank you for your feedback!

2022-05-27 15:27 UTC, daddyshortlegs requested changes
Good set of changes and nice to see you've removed the .idea folder. 
A nice feature of IntelliJ is the ability to auto format your code. I believe with Mac you can do command/option/L to do it, that would sort out the spaces and blank lines that I'm a stickler for.
I mentioned "global" variables (properties of the class). Try to avoid this if you can as this is effectively "state" and it's generally a good idea to avoid state whenever possible, especially when dealing with multi-threaded programs, like this one would become. You also don't need to declare your variables so far away from where they are used. The "scope" of your variables should be small.
Looks like your making good progress though.

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/request/RequestHandler.java
> +            if (Objects.equals(requestTarget, "/simple_get_with_body")) {
You could make this an else if, removing one level of indentation

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/request/RequestHandler.java
> +        response = responseStatusLine + CRLF + responseBody;
Nice use of a constant here (CRLF). You could do something similar with the Status code and test perhaps..

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/request/RequestHandler.java
> +    String CRLF = "\r\n";
Try to make this a constant. This is just a variable currently. The convention in java is for variables to be lowercase and constants to be UPPERCASE.

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/request/RequestHandler.java
> +    String response;
You may not need these variables to be "global" across this class. If you only use one of these variables in a method below and nowhere else, it maybe better to declare it in there. Keep declarations and usage of variables close to each other if you can.

Make variables a property of a class if it's necessary.

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/request/RequestHandler.java
> +        this.httpMethod = arrOfSplitResponseStr[0];
What happens here if the client request returns an empty array?

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/request/RequestHandler.java
> +        responseStatusLine = httpVersion + space + statusCode + space + statusText + CRLF;
As per my comment above, you can probably declare responseStatusLine here as I think it is only used in this method.

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/server/Server.java
> +    public void start() throws IOException {
Put an empty line above start. I know it's minor but I'm a stickler for blank lines :-)

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/server/Server.java
> +        }
I think you may be able to abstract some of the responsibilities in the loop as we discussed. It's looking on the right tracks though

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/server/ServerWrapper.java
> +            System.exit(1);
You may want to think about replacing printStackTrace and System.out.println with logback or something similar. In this particular section, this is a serious fatal error. You could replace lines 20 and 21 with something like Logback's log.fatal. That maybe the incorrect usage though. Generally we should avoid System.out and instead logging frameworks. Just not log4j!!! :-D

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/server/ServerWrapper.java
> +        }
I would replace these 2 print statements with a call to a logger, as previously mentioned.

2022-05-27 15:27 UTC, daddyshortlegs commented on src/main/java/org/httpserver/server/StdOutServerLogger.java
> +    public void printFailedToCreateServerSocket(int portNumber){
Blank lines between methods please :-)

2022-05-30 08:34 UTC, devlinmorrow approved these changes
I think this is a good PR which shows that you have developed your understanding of the setup of a server.

2022-05-30 09:03 UTC, fi-ya commented on src/main/java/org/httpserver/request/RequestHandler.java
> +        if(Objects.equals(requestTarget, "/simple_get")){
IntelliJ suggested refactoring as 'String values are compared using '==', not 'equals()'
<img width="1145" alt="Screenshot 2022-05-30 at 10 01 55" src="https://user-images.githubusercontent.com/69358550/170957440-79969eaa-c6e5-4bcb-8767-aa74add5cbb7.png">

2022-05-30 09:29 UTC, fi-ya commented on src/main/java/org/httpserver/request/RequestHandler.java
> +            if (Objects.equals(requestTarget, "/simple_get_with_body")) {
Yes, that works.

2022-05-30 09:42 UTC, fi-ya commented on src/main/java/org/httpserver/request/RequestHandler.java
> +    String response;
Thanks, I wasn't sure if i should make them attributes of the class, but i was thinking of the next possible uses and so made them global. But i have refactored and make them scoped to the method they are being used in.

2022-05-30 09:53 UTC, fi-ya commented on src/main/java/org/httpserver/request/RequestHandler.java
> +        this.httpMethod = arrOfSplitResponseStr[0];
It errors out. I will add an if statement which handles this case. (breaks out of if statement)

2022-05-30 09:53 UTC, fi-ya commented on src/main/java/org/httpserver/request/RequestHandler.java
> +        responseStatusLine = httpVersion + space + statusCode + space + statusText + CRLF;
I have removed all unessarary global variables.

2022-05-30 10:19 UTC, fi-ya commented on src/main/java/org/httpserver/server/ServerWrapper.java
> +            System.exit(1);
Great, thanks. I'll look into how to implement Logback in a Gradle project.

2022-05-30 10:20 UTC, fi-ya commented on src/main/java/org/httpserver/server/StdOutServerLogger.java
> +    public void printFailedToCreateServerSocket(int portNumber){
Command +Shift +L is fast becoming my fav shortcut! :)

2022-05-30 10:20 UTC, fi-ya commented on src/test/java/org/httpserver/server/ServerWrapperTest.java
> +        assertThrows(IllegalArgumentException.class, () -> serverWrapper.createServerSocket(-1));
Thanks!

2022-05-30 10:51 UTC, fi-ya commented on src/main/java/org/httpserver/client/ClientHandler.java
> +            clientConnectionCounter++;
Thanks I will include this test in the next PR

2022-05-30 10:55 UTC, merged