Bytes refactor
fi-ya/http-server pull request #20
Opened 2022-06-30 14:37 UTC by fi-ya

In this pull request I have refactored `ClientHandler,processSendResponse` to send to convert the response string into a bytes and write to `clientSocket.getOutputStream`. I have added byte attributes and setter methods to `Response` class. 

I will now be able to process files in the next PR. As i will be able to convert the file to string and create a Response object as normal and then convert the string to bytes which i will send to the client. 

🧪 Codecov coverage: 80%
❓ Gradle test coverage: Class:93% Method:87% Line:80%

2022-06-30 15:01 UTC, andy8thlight requested changes
A coupe of things I'm not sure of and there maybe a fairly big flaw in here around exception handling.

2022-06-30 15:16 UTC, fi-ya commented on src/test/java/org/httpserver/client/ClientHandlerTest.java
> +        assertEquals(Arrays.toString(expectedByte), Arrays.toString(expectedByte));
Yes, i can refactor to `"HTTP/1.1 200 OK".getBytes();`

2022-06-30 15:25 UTC, fi-ya commented on src/main/java/org/httpserver/client/ClientHandler.java
>      }
Thanks, ive added a try with resource statement

2022-07-01 08:37 UTC, devlinmorrow approved these changes
So the idea is to have the Response object contain both the String versions and the bytes versions? Yes I think that seems like it's one logical way of approaching this. I can imagine there could be some more robust testing of different things that can happen in a Response, and different ways it could fail, but for now I think this is good.

2022-07-01 08:59 UTC, merged